#+TITLE: Emacs config
#+AUTHOR: Ross A. Baker

* Security

[[https://glyph.twistedmatrix.com/2015/11/editor-malware.html][Your text editor is malware]].

** Configure TLS

Get certifi if you don't have it:

#+BEGIN_SRC sh
python -m pip install --user certifi
#+END_SRC

#+BEGIN_SRC emacs-lisp
(let ((trustfile
       (replace-regexp-in-string
        "\\\\" "/"
        (replace-regexp-in-string
         "\n" ""
         (shell-command-to-string "python -m certifi")))))
  (setq tls-checktrust t
        tls-program 
        (list
         (format "gnutls-cli%s --x509cafile %s -p %%p %%h"
                 (if (eq window-system 'w32) ".exe" "") trustfile))))
#+END_SRC

** Test it

If all is well, this test function will message =TLS configuration is secure=.

#+BEGIN_SRC emacs-lisp
(require 'cl)
(defun ross:test-tls-config ()
  (interactive)
  (let ((bad-hosts
	 (cl-loop for bad
	       in `("https://wrong.host.badssl.com/"
		    "https://self-signed.badssl.com/")
	       if (condition-case e
		      (url-retrieve
		       bad (lambda (retrieved) t))
		    (error nil))
	       collect bad)))
    (if bad-hosts
	(error (format "tls misconfigured; retrieved %s ok"
		       bad-hosts))
      (url-retrieve "https://badssl.com"
		    (lambda (retrieved)
                      (message "TLS configuration is secure")
                      t)))))
#+END_SRC

Running it on every init will slow us down, but better safe than sorry.

#+BEGIN_SRC emacs-lisp
(ross:test-tls-config)
#+END_SRC

* Packages

** https only

We will only use secure archives in this establishment.

#+BEGIN_SRC emacs-lisp
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
#+END_SRC

** use-package

Bootstraps the =use-package= macro.  We'll use it for almost
everything else.

#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))
(require 'diminish)                ;; if you use :diminish
(require 'bind-key)                ;; if you use any :bind variant
#+END_SRC

* Better defaults

: this package attempts to address the most obvious of deficiencies in
: uncontroversial ways that nearly everyone can agree upon

Maybe we'll dissect this later, but this gets us a humane interface
now.

#+BEGIN_SRC emacs-lisp
(use-package better-defaults
  :ensure t)
#+END_SRC

* Apperance

** Theme

A dark, tasteful, and relatively complete theme.

#+BEGIN_SRC emacs-lisp
(use-package color-theme-sanityinc-tomorrow
  :ensure t
  :init
  (color-theme-sanityinc-tomorrow-night))
#+END_SRC

** Font

Fira Code is a nice font with ligature support.

#+BEGIN_SRC emacs-lisp
(when (window-system)
  (set-default-font "Fira Code"))
#+END_SRC

*** Enable ligatures

This works on the railwaycat Mac port.  We'll need to do some [[https://github.com/tonsky/FiraCode/wiki/Setting-up-Emacs][more
work]] on other platforms.

#+BEGIN_SRC emacs-lisp
(mac-auto-operator-composition-mode)
#+END_SRC

** Completion

*** Ivy

Ivy is a generic completion mechanism for Emacs.

#+BEGIN_SRC emacs-lisp
(use-package ivy
  :ensure t
  :diminish ivy-mode
  :config
  (ivy-mode 1))
#+END_SRC

*** Counsel

Counsel integrates several common commands with ivy.

#+BEGIN_SRC emacs-lisp
(use-package counsel
  :ensure t
  :bind ("M-x"     . counsel-M-x)
        ("C-x C-f" . counsel-find-file)
        ("<f1> f"  . counsel-describe-function)
        ("<f1> v"  . counsel-describe-variable)
        ("<f1> l"  . counsel-find-library)
        ("<f2> i"  . counsel-info-lookup-symbol)
        ("<f2> u"  . counsel-unicode-char)
        ("C-c g"   . counsel-git)
        ("C-c j"   . counsel-git-grep)
        ("C-c k"   . counsel-ag)
        ("C-x l"   . counsel-locate))
#+END_SRC

*** Swiper

Swiper is an ivy-integrated isearch replacement.

#+BEGIN_SRC emacs-lisp
(use-package swiper
  :ensure t
  :bind ("C-r" . swiper)
        ("C-s" . swiper))
#+END_SRC

* Programming

** Magit

#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t
  :bind (("C-x g" . magit-status)))
#+END_SRC

** Languages

*** Scala

A more spartan Scala environment than Ensime.  Let's try it on for
size.

#+BEGIN_SRC emacs-lisp
(use-package scala-mode
  :ensure t
  :interpreter
  ("scala" . scala-mode))

(use-package sbt-mode
  :ensure t
  :commands sbt-start sbt-command
  :config
  ;; WORKAROUND: https://github.com/ensime/emacs-sbt-mode/issues/31
  ;; allows using SPACE when in the minibuffer
  (substitute-key-definition
   'minibuffer-complete-word
   'self-insert-command
   minibuffer-local-completion-map))
#+END_SRC

*** Yaml

For those times you need JSON with an 84-page spec.

#+BEGIN_SRC emacs-lisp
(use-package yaml-mode
  :ensure t)
#+END_SRC
